### ISSUE TITLE
Bower package name

### ISSUE THREAD

**Issue by Jasonkoolman** [fspoettel/hagrid#63]
@fspoettel Sorry in advance for submitting an issue, but I didn't find any other way to get in contact with you. While registering a bower package for a brand new front-end framework that I'm releasing named "Fundament", I found out that this repo already holds that name, although `bower install hagrid` works too and may be more suited as well. To keep it short: is it possible that you could unregister your bower package under the name Fundament? It would be very kind of you.

Greetings from your neighbouring country!

**Comment by fspoettel** [comment]
Hey, yes of course. The package was named fundament originally, back when bower did not allow unregistering packages. I will do that tomorrow and get back to you.

**Comment by fspoettel** [comment]
@Jasonkoolman see: https://github.com/bower/registry/issues/240. I cannot do it manually and have to wait for this issue to get resolved.

**Comment by fspoettel** [comment]
The package is unregistered, good luck with your project!
